use case:credentials: monitor Linux capability checks
cilium/tetragon pull request #1189
Opened 2023-07-06 10:41 UTC by tixxdz

2023-08-17 08:05 UTC, kkourt requested changes
Thanks, LGTM overall!

Find some suggestions below.

2023-08-17 08:05 UTC, kkourt commented on docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
> +In order to reduce the number of events, the [creds-capability-usage](https://raw.githubusercontent.com/cilium/tetragon/main/examples/tracingpolicy/process-credentials/creds-capability-usage.yaml) ra
```suggestion
Tracing policies as the one used here, may emit a high number of events.
To reduce events, the [creds-capability-usage](https://raw.githubusercontent.com/cilium/tetragon/main/examples/tracingpolicy/process-credentials/creds-capability-usage.yaml) rate limits events to 1 minute. More details about rate-limiting can be found in the [tracing policy documentation]({{< ref "docs/concepts/tracing-policy/" >}}).
```

2023-08-20 20:28 UTC, tixxdz commented on docs/content/en/docs/use-cases/security-profiles/_index.md
> +linkTitle: "Security Profiles"
Thinking about:
1. Recording system calls
2. Some generic sandbox examples , restricting namespaces and others

We surely can improve alter

2023-08-20 20:50 UTC, tixxdz commented
> Thanks, LGTM overall!
> 
> Find some suggestions below.

Thanks for the review, all comments fixed.

2023-08-21 06:04 UTC, kkourt approved these changes

2023-08-21 10:48 UTC, mtardy reviewed
Thanks!! Here are a few docs comments

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
> +```
````suggestion
```shell-session
kubectl get pods -A
```

The output should be similar to:
```
NAMESPACE            NAME                                         READY   STATUS    RESTARTS   AGE
default              deathstar-54bb8475cc-6c6lc                   1/1     Running   0          2m54s
default              deathstar-54bb8475cc-zmfkr                   1/1     Running   0          2m54s
default              tiefighter                                   1/1     Running   0          2m54s
default              xwing                                        1/1     Running   0          2m54s
kube-system          tetragon-sdwv6                               2/2     Running   0          27m
```
````

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/_index.md
> +The [Record Linux Capabilities Usage](/docs/use-cases/security-profiles/record-linux-capabilities) guide
```suggestion
The [Record Linux Capabilities Usage]({{< ref "/docs/use-cases/security-profiles/record-linux-capabilities" >}}) guide
```

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
> +```
````suggestion
```shell-session
dmesg
```

The output should be similar to:
```
dmesg: klogctl: Operation not permitted
```
````

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
> +* `return`: indicates via the `int_arg` if the capability check succeeded or failed. `0` means it succeeded and the access was granted while `-1` means it failed and the operation was denied.
Usually, I would advise to not put space between list items as it can break markdown listing quite unexpectedly but it seems to work here.

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
> +```bash
````suggestion
```shell-session
````

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/record-linux-capabilities.md
> +   * [ns]({{< ref "/docs/reference/grpc-api#namespace" >}}): details the information about the namespace. `is_host` indicates that the target user namespace where the capability is required is the ho
```suggestion
   * [`ns`]({{< ref "/docs/reference/grpc-api#namespace" >}}): details the information about the namespace. `is_host` indicates that the target user namespace where the capability is required is the host namespace.
```

2023-08-21 10:48 UTC, mtardy commented on docs/content/en/docs/use-cases/security-profiles/_index.md
> +linkTitle: "Security Profiles"
jfyi you don't need to specify both title and linkTitle if they are the same

2023-08-25 12:39 UTC, tixxdz commented
thanks @mtardy

2023-08-25 12:40 UTC, merged