Update the CRD schema version
cilium/tetragon pull request #1409
Opened 2023-08-31 07:50 UTC by tpapagian

2023-08-31 08:12 UTC, kkourt commented on .github/ISSUE_TEMPLATE/release_template.md
> +
```suggestion
- [ ] If you branch out vX.Y, create a new PR in the `main` branch to update [CustomResourceDefinitionSchemaVersion](https://github.com/cilium/tetragon/blob/6f2809c51b3fbd35b1de0a178f1e3d0b18c52bcc/pkg/k8s/apis/cilium.io/v1alpha1/register.go#L18) to `vX.Y+1.0`.

```

2023-08-31 08:15 UTC, kkourt requested changes
Thanks!

2023-08-31 08:23 UTC, tpapagian commented on .github/ISSUE_TEMPLATE/release_template.md
> +
Why do we need `"Once PR is merged, tag the first commit in master which is not in the `X.Y` branch as `vX.Y+1.0-pre.0`."`?

2023-09-01 07:09 UTC, kkourt commented on .github/ISSUE_TEMPLATE/release_template.md
> +
Not sure I'm following. Here's what I'm thinking:

```mermaid

gitGraph
    commit
    commit
    branch "v0.10"
    checkout main
    commit id: "CRD -> v0.11.0" tag: "v0.11.0-pre.0"
    commit
    commit
    checkout "v0.10"
    commit
    commit
    commit tag: "v0.10.1"
```

2023-09-01 07:10 UTC, kkourt commented on .github/ISSUE_TEMPLATE/release_template.md
> +
So there is the CRD change commit that we can tag. Makes sense?

2023-09-01 07:10 UTC, kkourt approved these changes

2023-09-01 07:14 UTC, merged