chore: unloadpolicy after load
cilium/tetragon pull request #1916
Opened 2023-12-26 06:38 UTC by sadath-12

This pr will unload the policy that was loaded during the test which ultimately closes the issue #1771

2024-01-04 09:36 UTC, tixxdz commented
Thanks for the fix, can you please make it in one single patch? also maybe try to lookup for other LoadCRDString() calls missing the UnloadCRDString() and fix them **if they are bugs**.

Much appreciated @sadath-12

2024-01-04 10:02 UTC, sadath-12 commented
Updated . Thanks @tixxdz

2024-01-08 15:01 UTC, willfindlay requested changes

2024-01-08 15:01 UTC, willfindlay commented on tests/e2e/tests/skeleton/skeleton_test.go
> +		Assess("Run Workload", func(ctx context.Context, _ *testing.T, c *envconf.Config) context.Context {
```suggestion
		Assess("Uninstall policy", func(ctx context.Context, _ *testing.T, c *envconf.Config) context.Context {
```

2024-01-08 15:01 UTC, willfindlay commented on tests/e2e/tests/policyfilter/policyfilter_test.go
> +		Assess("uninstall policy", func(ctx context.Context, _ *testing.T, c *envconf.Config) context.Context {
```suggestion
		Assess("Uninstall policy", func(ctx context.Context, _ *testing.T, c *envconf.Config) context.Context {
```

2024-01-08 15:01 UTC, willfindlay commented on tests/e2e/tests/policyfilter/policyfilter_test.go
> +		Assess("uninstall policy", func(ctx context.Context, _ *testing.T, c *envconf.Config) context.Context {
```suggestion
		Assess("Uninstall policy", func(ctx context.Context, _ *testing.T, c *envconf.Config) context.Context {
```

2024-01-08 15:26 UTC, sadath-12 commented
Thanks for helping identify mistakes and Improve this @willfindlay

2024-01-08 15:27 UTC, tixxdz approved these changes
LGTM, thanks @willfindlay for review

2024-01-10 13:37 UTC, willfindlay approved these changes

2024-01-10 13:37 UTC, merged