Introduce install/kubernetes/Makefile
cilium/tetragon pull request #1930
Opened 2024-01-04 06:38 UTC by sadath-12

Addresses part 1 and part 2 of issue: #1847

2024-01-05 18:32 UTC, lambdanis requested changes
Thanks for the PR! I left a few comments regarding Makefile structure mostly.

2024-01-05 18:32 UTC, lambdanis commented on .github/ISSUE_TEMPLATE/release_template.md
> +      make -C install/kubernetes all
It can be simplified to `make -C install/kubernetes` here and in other places.

2024-01-05 18:32 UTC, lambdanis commented on install/kubernetes/Makefile
> +endef
These commands are used only once, so I don't think there is a need to create aliases for them, they can be just pasted directly into the rules.

2024-01-05 18:32 UTC, lambdanis commented on install/kubernetes/Makefile
> +endef
I think it should rather be
```
HELM := docker run --rm -v $(TETRAGON_CHART):/apps alpine/helm:3.3.4
```

2024-01-05 18:32 UTC, lambdanis commented on install/kubernetes/Makefile
> +	$(HELM) dependency update .
I would rather have a separate target (e.g. `deps`) for this as it's not exactly a part of linting.

2024-01-05 18:32 UTC, lambdanis commented on install/kubernetes/Makefile
> +	$(HELM) template tetragon . | $(KUBECONFORM) --strict --schema-location default
This can be a part of the `lint` target, no need to separate it I think.

2024-01-06 10:04 UTC, sadath-12 commented
Thank you @lambdanis  for improving this

2024-01-08 10:04 UTC, lambdanis approved these changes
looks good to me, thanks!

2024-01-08 14:59 UTC, willfindlay approved these changes
Awesome

2024-01-08 18:45 UTC, merged