docs:policylibrary: more examples on privileges escalation and execution
cilium/tetragon pull request #2067
Opened 2024-02-05 20:57 UTC by tixxdz

2024-02-08 10:56 UTC, sharlns requested changes
LGTM, thank you! Please move the configuration details out from the "Policy Library" and just reference the corresponding page.

2024-02-08 10:56 UTC, sharlns commented on docs/content/en/docs/policy-library/observability/_index.md
> +Run Tetragon with `enable-process-creds` setting set to enable visibility
This configuration level doesn't belong to the "Policy Library" section. Can you please point just a reference here to the documentation where you can enable credentials in processX events?

2024-02-08 10:56 UTC, sharlns commented on docs/content/en/docs/policy-library/observability/_index.md
> +Run Tetragon with `enable-process-creds` setting set to enable visibility
The same comment applies here. This level of configuration details doesn't belong to the "Policy Library".

2024-02-14 10:01 UTC, tixxdz commented on docs/content/en/docs/policy-library/observability/_index.md
> +Run Tetragon with `enable-process-creds` setting set to enable visibility
> This level of configuration details doesn't belong to the "Policy Library" section. Can you please point just a reference here to the documentation where you can enable credentials in processX events?

I understand but this adds more work as right now we don't have this section, I will try to hack something up but don't want to delay more the PR.

2024-02-14 16:48 UTC, tixxdz commented on docs/content/en/docs/policy-library/observability/_index.md
> +Run Tetragon with `enable-process-creds` setting set to enable visibility
I added configuration section hope it's ok ;-)

2024-02-14 16:49 UTC, tixxdz commented
> LGTM, thank you! Please move the configuration details out from the "Policy Library" and just reference the corresponding page.

Thanks @sharlns for the review, I did that. If it feels not perfect then let's discuss that in separate issue or PR please

2024-02-15 11:17 UTC, sharlns approved these changes
LGTM. Amazing work, thank you! 🙏

2024-02-15 11:46 UTC, mtardy approved these changes
Thanks, I haven't checked the content just some nits on the form. 

If you could also wrap consistently the text around 80 chars that would be nice. Some paragraphs are in your PR while others aren't.

On another topic I find https://tetragon.io/docs/policy-library/observability/ really hard to read, maybe we could present that differently but that's another topic :)!

2024-02-15 11:46 UTC, mtardy commented on docs/content/en/docs/installation/configuration.md
> +## Configuration
you don't need to repeat the title
<img width="669" alt="image" src="https://github.com/cilium/tetragon/assets/11256051/4a46f3b7-28fc-460d-a4fd-2e1735138b31">

2024-02-15 11:46 UTC, mtardy commented on docs/content/en/docs/installation/configuration.md
> +### Enable Process Credentials
if you remove the previous title, make those `##` (and the other one)

2024-02-15 11:46 UTC, mtardy commented on docs/content/en/docs/installation/configuration.md
> +{{< tab docker >}}
```suggestion
{{< tab Docker >}}
```

2024-02-15 11:46 UTC, mtardy commented on docs/content/en/docs/installation/configuration.md
> +{{< tab docker >}}
```suggestion
{{< tab Docker >}}
```

2024-02-15 22:19 UTC, tixxdz commented
> Thanks, I haven't checked the content just some nits on the form.
> 
> If you could also wrap consistently the text around 80 chars that would be nice. Some paragraphs are in your PR while others aren't.

Thank you @mtardy I did and fixed all others ;-)
 
> On another topic I find https://tetragon.io/docs/policy-library/observability/ really hard to read, maybe we could present that differently but that's another topic :)!

Agree, need to not look at it for a moment then read it again ;-D !

2024-02-15 23:41 UTC, merged