feat: update home page design
cilium/tetragon pull request #2374
Opened 2024-04-25 08:11 UTC by yasell

This PR updates the style and design of the home page.

2024-04-25 09:04 UTC, mtardy reviewed
Thanks, that looks way better, especially since we switched logos!

I needed to remove a lot of the custom style because Docsy had a breaking change moving to Bootstrap 5 in `v0.7.0` and most of the style written was broken https://github.com/google/docsy/releases/tag/v0.7.0. I hope this time, this is more resilient for future updates.

I have a few first comments, but I think this PR should be a draft given you have a lot of placeholders and links that don't work on the page, so I'll convert it to draft as of now, you can mark it ready once you want a full review.

I would say as long as the homepage doesn't affect how the rest of the documentation looks (typically the global font change isn't great) I'm super fine with it and happy that someone who can write serious design and CSS rewrote that.

2024-04-25 14:53 UTC, paularah commented on docs/static/images/home/hero-illustration.png
I think it works, since it uses the new logo. The cilium website has a similar illustration.

2024-04-25 16:10 UTC, yasell commented on docs/assets/scss/_variables_project.scss
> +$google_font_family: "Manrope:400,500,600,700";
I went back to the original `Open Sans` for the whole site and made `Manrope` just for the main page (with header and footer).

2024-04-25 17:13 UTC, mtardy commented on docs/assets/scss/_variables_project.scss
> +$google_font_family: "Manrope:400,500,600,700";
Thanks I appreciate :)

2024-05-08 08:33 UTC, xmulligan commented
Sorry I know this is a little late in the process, but can we had a section like the one below to the website under the first section? "We are a proud CNCF project"

Some people don't realize this and it would be great to get on the website

<img width="716" alt="Screenshot 2024-05-08 at 10 31 46" src="https://github.com/cilium/tetragon/assets/29048870/9acd127d-0629-406d-810e-5eb62278d2ee">

2024-06-03 10:14 UTC, mtardy commented
Just fyi, I updated Docsy and Hugo version, you might need to rebase on top of main (for that PR https://github.com/cilium/tetragon/pull/2497). I checked, and nothing breaks on your homepage, you just need to merge some commits during the rebase but it should be trivial, just accept both changes all the time.

2024-06-03 12:49 UTC, mtardy reviewed
Can you rebase on main and squash the commits? thanks!!

2024-06-03 12:49 UTC, mtardy commented on docs/assets/scss/_variables_project.scss
> +//$google_font_family: "Manrope:400,500,600,700";
maybe just remove that completely if it's already in your homepage CSS.

2024-06-04 09:02 UTC, mtardy requested changes
I was going to merge but I did some checks and found some issues! Again if you fix this, feel free to squash your commits into one. Thanks a lot, overall it's night and day with the current homepage.

2024-06-04 10:53 UTC, mtardy commented on docs/content/en/_index.html
> +                            <li class="updates__inner-item updates__inner-item--cornflower">Conference</li>
any reason we don't have the 
`<li class="updates__inner-item updates__inner-item--decor">External</li>` here?

2024-06-04 10:53 UTC, mtardy commented on docs/content/en/_index.html
> +                        <span class="tabs__tab-title">Install on any Linux OS system </span>
you could have used CTRL+F here
```suggestion
                        <span class="tabs__tab-title">Install on any Linux system </span>
```

2024-06-04 10:53 UTC, mtardy commented on docs/content/en/_index.html
> +                    {{< tab-code header="Linux OS" lang="shell" >}}
```suggestion
                    {{< tab-code header="Linux" lang="shell" >}}
```

2024-06-04 10:53 UTC, mtardy commented on docs/content/en/_index.html
> +                    {{< tab-code header="Copy a container" lang="shell" >}}
```suggestion
                    {{< tab-code header="Container" lang="shell" >}}
```

2024-06-04 10:53 UTC, mtardy commented on docs/content/en/_index.html
> +                    <span class="tabs__button-mobile" aria-hidden="true">Copy container</span>
```suggestion
                    <span class="tabs__button-mobile" aria-hidden="true">Container</span>
```

2024-06-04 10:53 UTC, mtardy commented on docs/content/en/_index.html
> +            <a class="button button--text" href=/docs/resources#conference-talks">
When I click in the preview it opens the URL `https://deploy-preview-2374--tetragon.netlify.app/docs/resources/#conference-talks%22` with the `"` symbol at the end, thus the anchor does not work, do you know why? can you fix this?

2024-06-04 11:04 UTC, mtardy approved these changes
Thanks, it looks fantastic! :)

2024-06-04 11:08 UTC, merged