Create a Pull Request Template for the project
cilium/tetragon pull request #2387
Opened 2024-04-28 02:52 UTC by paularah

Fixes: #1929

Adds a pull request template to provide information on how to contribute to Tetragon.

2024-04-29 09:58 UTC, lambdanis requested changes
Thank you @paularah :bowing_woman: 

I left one small suggestion. Also, you need to amend the commit message in order to pass the CI - write a title and add a sign-off. Your PR contains instructions on how to do that :)

2024-04-29 09:58 UTC, lambdanis commented on .github/pull_request_template.md
> +- [ ] All commits contain a well written commit description including a title,
```suggestion
- [ ] All commits contain a well written commit message including a title,
```

2024-05-03 13:45 UTC, tixxdz reviewed
LGTM when @lambdanis and other comments are fixed.

Thank you ;-)

2024-05-03 13:45 UTC, tixxdz commented on .github/pull_request_template.md
> +- [ ] All commits contain a well written commit description including a title,
plus commit log

2024-05-24 14:37 UTC, paularah commented
@lambdanis should be all good now.

2024-05-25 15:23 UTC, lambdanis approved these changes
Looks good, thank you!

2024-05-25 15:23 UTC, merged