Update Getting Started guide
cilium/tetragon pull request #2721
Opened 2024-07-23 21:07 UTC by scottslowe

### Description
This PR updates the Getting Started guide for consistency throughout all sections.

Here is the full changeset:

`execution.md`:
Remove language specifier for fenced codeblock.

`file-events.md`:
Add instructions for single-node and multi-node K8s clusters. Clean up Docker instructions.
Ensure consistent header levels.
Minor fixes in spelling and grammar.

`network.md`:
Add EKS, AKS instructions for getting service CIDR. Add instructions for single-node and multi-node K8s clusters. Ensure consistent header levels.
Minor fixes in spelling and grammar.

`enforcement.md`:
Reorganize content to improve flow.
Add EKS, AKS instructions for getting service CIDR. Add instructions for single-node and multi-node K8s clusters. Ensure consistent header levels.
Minor fixes in spelling and grammar.

No release notes/changelog entries necessary.

2024-07-24 09:28 UTC, mtardy requested changes
Thanks, that's an amazing change! This time you could have separated the patches by commits but it's completely fine like that.

There's one thing I don't get:
> Remove language specifier for fenced codeblock.

In many places you removed the `shell` specifier, it's only supposed to be removed when you put output of commands, the commands themselves need this to appear correctly. I'm not sure why you removed them in some places, I didn't node all of them.

Once we have some things fixed I'll be happy to merge this :) thanks again!

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/enforcement.md
> +events. Using in-kernel filtering in Tetragon provides a key performance
so Tetragon doesn't really "enforce restrictions on events", it enforces restriction directly on the kernel functions. The events are just a by-product of Tetragon. Maybe the wording could be changed here?

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/enforcement.md
> +```
In this case you do want `shell`.

````suggestion
```shell
````

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/enforcement.md
> +```
````suggestion
```shell
````

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/enforcement.md
> +```
````suggestion
```shell
````

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/enforcement.md
> +  quay.io/cilium/tetragon:latest
you could make use of `{{< latest-version >}}` if you want here that will inject the latest released version of Tetragon
```suggestion
  quay.io/cilium/tetragon:{{< latest-version >}} 
```

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/execution.md
> +```
again here

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/file-events.md
> +  quay.io/cilium/tetragon:latest
same
```suggestion
  quay.io/cilium/tetragon:{{< latest-version >}}
```

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/network.md
> +These instructions assume you already have Tetragon running in either Kubernetes or Docker, and that you have deployed the Cilium demo application.
that's a nit but if you can wrap here

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/network.md
> +```
````suggestion
```shell
````

2024-07-24 09:28 UTC, mtardy commented on docs/content/en/docs/getting-started/network.md
Is there a way we could combine Kubernetes and Docker bare-metal using panes here as we did in other guides instead of two separate sections?

2024-07-24 14:33 UTC, scottslowe commented on docs/content/en/docs/getting-started/network.md
Yes. It would be a pretty fair amount of work and would take a fair amount of time, so if possible I'd like to see these changes get merged and I'll file a separate PR targeting this request specifically. Thoughts?

2024-07-24 14:41 UTC, scottslowe commented
@mtardy I think I've incorporated all your requested changes. I did not switch to using `{{< latest-version >}}`; if you feel strongly that we need to make that change, let me know. Otherwise, I believe all changes EXCEPT reworking the Docker/K8s networking section have been addressed (see comment above regarding that work).

2024-07-24 14:43 UTC, mtardy commented on docs/content/en/docs/getting-started/network.md
yeah that's perfectly fine!

2024-07-24 14:46 UTC, mtardy reviewed
Thanks a lot that's great! Could you squash your commits https://tetragon.io/docs/contribution-guide/submitting-a-pull-request/#commit-changes ? With merge rebase so we squash commits related to feedback.

2024-07-25 09:09 UTC, mtardy approved these changes
Many thanks!

2024-07-25 09:09 UTC, merged