feat: add banner to community meetings and move tetragon slides
cilium/tetragon pull request #2801
Opened 2024-08-15 12:40 UTC by annaindistress

### Description

Add banner before header and move slider section after community links at the homepage

<img width="988" alt="image" src="https://github.com/user-attachments/assets/42e96d78-c6ba-42dc-85ee-6890f4863160">

<img width="628" alt="image" src="https://github.com/user-attachments/assets/f7571922-af98-4928-a381-6fca0e6aa12e">

2024-08-15 12:54 UTC, paularah commented
@annaindistress can you request a review from me?

2024-08-15 15:17 UTC, annaindistress commented
> @annaindistress can you request a review from me?

It seems that I'm unable to select reviewers

<img width="323" alt="image" src="https://github.com/user-attachments/assets/0fd7cdbd-a2c7-46c2-8dd9-99d7345a9e15">

2024-08-15 18:07 UTC, lambdanis commented
@paularah Done. FYI, only Cilium GH org members can assign reviewers.

2024-08-15 20:40 UTC, paularah commented
> @paularah Done. FYI, only Cilium GH org members can assign reviewers.

oopsie. thanks

2024-08-15 20:41 UTC, paularah approved these changes
LGTM

2024-08-16 08:44 UTC, mtardy requested changes

2024-08-16 08:44 UTC, mtardy commented on docs/_vendor/github.com/google/docsy/assets/scss/_community-banner.scss
hey, please don't touch files under `_vendor`. With Hugo, you can override/extend them using layouts/assets from the top folder.

2024-08-16 08:45 UTC, mtardy commented on docs/content/en/_index.html
> +                            Tetragon is a <b>sub-project under</b>
you also have a lot of whitespaces changes here, not sure it's intended.

2024-08-16 14:29 UTC, annaindistress commented on docs/_vendor/github.com/google/docsy/assets/scss/_community-banner.scss
Thanks! I moved the markup to the `/layouts` folder and the styles to `/assets/scss`. 

I also made a minor update to the mobile styles so that the banner doesn't take up too much space

2024-08-16 14:33 UTC, mtardy approved these changes
Thanks! looks good like that :)

2024-08-16 14:36 UTC, mtardy commented
Ah you might have to rebase the LinkedIn PR sorry I forgot to look at it after you pushed changes. Let's merge this one as it's bigger.

2024-08-16 14:36 UTC, merged