Add CEL filter to the CLI, fixes #3112
cilium/tetragon pull request #3124
Opened 2024-11-15 18:42 UTC by knrc

Fixes 3112

### Description

Integrate the existing CEL filtering capability into the CLI

### Changelog

2024-11-18 14:23 UTC, knrc commented
> Hi,
> 
> Thanks for the PR!
> 
> It seems to me that this PR attempts to add support for CEL filters in the export filters rather than the CLI (`tetra`). Could you please add more details about what the PR attempts to do? An example of how it works in the commit message would be very helpful in that regard.

Sorry, my mistake.  I picked this up at the Contribfest, found that these filters were missing the CEL integration and submitted the fix.  I'll tidy this up, and fix the CLI issue, some time over the next few days.

In the meantime I've converted this to a draft

2024-11-28 17:21 UTC, knrc commented
> It seems to me that this PR attempts to add support for CEL filters in the export filters rather than the CLI (`tetra`). Could you please add more details about what the PR attempts to do? An example of how it works in the commit message would be very helpful in that regard.

@kkourt I've updated the PR to also include the CLI integration, the `tetra getevents` command will now accept `--cel-expression` arguments to enable filtering of events by CEL expressions.

2024-12-03 09:03 UTC, kkourt requested changes
Thanks!

Can you please add an example usage in the commit message?

Also, can you put the "Fixes: <issue>" in the PR message" rather than the commit title?

2024-12-06 00:53 UTC, knrc commented
> Can you please add an example usage in the commit message?
> 
> Also, can you put the "Fixes: " in the PR message" rather than the commit title?

Commit message should now be updated

2024-12-06 12:01 UTC, olsajiri approved these changes

2025-01-14 11:58 UTC, kkourt approved these changes
Thanks!

2025-01-14 11:58 UTC, merged