fix: update cwd_read to assign vfsmnt correctly
cilium/tetragon pull request #3261
Opened 2024-12-27 04:01 UTC by arthur-zhang

Fixes 

### Description
cwd_read do not assign data->vfsmnt correctly.  in container env, the cwd_read will obtain all the file path to root like when read `/tmp/tetragon`. it will make arg match failed

```
/scon/containers/01J6HEV7R29R4WXXS1N2CS9ATP/rootfs/tmp/tetragon
```

in the old code, mnt is pointer to the old data->mnt, which is not correct.
```
struct mount *mnt = data->mnt;
...
if (data->mnt != parent) {
    probe_read(&data->dentry, sizeof(data->dentry),
			    _(&mnt->mnt_mountpoint));
    data->mnt = parent;
    probe_read(&data->vfsmnt, sizeof(data->vfsmnt),
			    _(&mnt->mnt));
    return 0;
}
```
### Changelog

```
todo!
```

2025-01-03 11:27 UTC, olsajiri commented
> Fixes
> ### Description
> 
> cwd_read do not assign data->vfsmnt correctly.
> 
> reproduce:
> 
> ```
> sudo mount -t nfs  x.x.x.x:/data/dev/nfs_dir /home/arthur/my_run
> 
> $ mount -t
> x.x.x.x:/data/dev/nfs_dir on /home/arthur/my_run
> /dev/nvme0n1p5 on /home type ext4 (rw,relatime)
> ```
> 
> and cat a file in my_run dir
> 
> ```
> cat /home/arthur/my_run/a.txt
> ```
> 
> in tetragon side, it will get a path : `/home/home/arthur/my_run/a.txt`, but it should be `/home/arthur/my_run/a.txt`
> 
> ```
> cat-2152134 [003] d...1 3725192.671779: bpf_trace_printk: copy path: /home/home/arthur/my_run/a.txt
> ```
> 
> and in another production env, i found it will get path more than expected when i cat `/tmp/tetragon`. the prefix `/scon/containers/01J6HEV7R29R4WXXS1N2CS9ATP/rootfs/` should not be obtained.
> 
> ```
> /scon/containers/01J6HEV7R29R4WXXS1N2CS9ATP/rootfs/tmp/tetragon
> ```
> 
> in the old code, mnt is pointer to the old data->mnt, which is not correct.
> 
> ```
> struct mount *mnt = data->mnt;
> ...
> if (data->mnt != parent) {
>     probe_read(&data->dentry, sizeof(data->dentry),
> 			    _(&mnt->mnt_mountpoint));
>     data->mnt = parent;
>     probe_read(&data->vfsmnt, sizeof(data->vfsmnt),
> 			    _(&mnt->mnt));
>     return 0;
> }
> ```
> 
> ### Changelog
> 
> ```
> Fix vfsmnt assign bug in bpf/process/bpf_process_event.h
> ```

@arthur-zhang please put all this in the commit changelog, also any chance you could add test the issue? thanks

2025-01-03 14:47 UTC, olsajiri commented on bpf/process/bpf_process_event.h
> +			data->vfsmnt = &parent->mnt;
ok,  parent->mnt is not pointer but actual vfsmnt object embedded in mount struct,
so we can just take the address from parent.. but I think you still need to use _() to get CORE involved

2025-01-03 14:50 UTC, arthur-zhang commented on bpf/process/bpf_process_event.h
> +			data->vfsmnt = &parent->mnt;
OK， i will fix it

2025-01-08 18:29 UTC, olsajiri requested changes
please add missing changelog and it's good to go, thanks

2025-01-09 13:53 UTC, merged