fix: nspid assign is not correct
cilium/tetragon pull request #3267
Opened 2024-12-31 08:50 UTC by arthur-zhang

### Description
`curr->nspid` should be obtained from the child `task` arguments, not from the current `task_struct` (the parent process). 

This will lead to a mismatch between `pid` and `nspid`.

```c
__attribute__((section("kprobe/wake_up_new_task"), used)) int
BPF_KPROBE(event_wake_up_new_task, struct task_struct *task) {
struct execve_map_value *curr;

  tgid = BPF_CORE_READ(task, tgid); 
  curr->key.pid = tgid; // curr->key.pid is obtained from the task argument
  // is not correct.
  curr->nspid = get_task_pid_vnr(); // curr->nspid is obtained from the current task_struct (parent)!
}
```

### Changelog

```
todo
```

2025-01-03 14:29 UTC, olsajiri requested changes
nice catch, please put the PR description into commit changelog

2025-01-03 14:29 UTC, olsajiri commented on bpf/lib/bpf_task.h
> +	return get_task_pid_vnr_by_task(task);
please put extra line after declaration

2025-01-03 14:37 UTC, arthur-zhang commented on bpf/lib/bpf_task.h
> +	return get_task_pid_vnr_by_task(task);
done

2025-01-03 14:54 UTC, olsajiri commented on bpf/lib/bpf_task.h
> +	return get_task_pid_vnr_by_task(task);
there needs to be empty line after declrations, so something like:

```
--- a/bpf/lib/bpf_task.h
+++ b/bpf/lib/bpf_task.h
@@ -98,6 +98,7 @@ FUNC_INLINE __u32 get_task_pid_vnr_by_task(struct task_struct *task)
 FUNC_INLINE __u32 get_task_pid_vnr_curr(void)
 {
        struct task_struct *task = (struct task_struct *)get_current_task();
+
        return get_task_pid_vnr_by_task(task);
 }
```

2025-01-06 02:39 UTC, arthur-zhang commented on bpf/lib/bpf_task.h
> +	return get_task_pid_vnr_by_task(task);
done modify

2025-01-06 08:19 UTC, olsajiri commented on bpf/lib/bpf_task.h
> +	return get_task_pid_vnr_by_task(task);
ok, also please add the missing changelog, thanks

2025-01-08 18:28 UTC, olsajiri requested changes
please add missing changelog and it's good to go, thanks

2025-01-09 02:37 UTC, arthur-zhang commented
> please add missing changelog and it's good to go, thanks

Does current pr changelog meet your expectations?

2025-01-09 07:23 UTC, olsajiri commented
> > please add missing changelog and it's good to go, thanks
> 
> Does current pr changelog meet your expectations?

pr changelog is fine, but there's nothing in commit changelog

2025-01-09 13:47 UTC, olsajiri approved these changes

2025-01-09 13:49 UTC, merged