hubble-fgs: Add event config map
cilium/tetragon pull request #53
Opened 2022-05-22 21:13 UTC by olsajiri

Getting rid of extra configuration inside BTF and moving it to map.

The new internal config_map map is loaded for both tracepoints
and kprobes and loaded with config data at zero index.

Signed-off-by: Jiri Olsa [jolsa@kernel.org](mailto:jolsa@kernel.org)

2022-05-29 07:54 UTC, olsajiri commented
I'm now suddenly getting this panic:
`panic: test timed out after 10m0s`

need to figure this out, moving to draft again

2022-05-29 22:19 UTC, olsajiri commented
> I'm now suddenly getting this panic: `panic: test timed out after 10m0s`
> 
> need to figure this out, moving to draft again

must be my setup, increased the timeout and all's passed

2022-05-30 16:03 UTC, kkourt commented
> > I'm now suddenly getting this panic: `panic: test timed out after 10m0s`
> > need to figure this out, moving to draft again
> 
> must be my setup, increased the timeout and all's passed

Did a `make test` on my machine (with `go clean -testcache` before), and this is what I got:

`main`: 51.46s user 133.45s system 60% cpu 5:06.75 total
#53:  49.39s user 157.57s system 63% cpu 5:28.15 total

so there does not seem to be a big difference between the two.

2022-05-30 17:05 UTC, willfindlay commented
I've seen local test timeouts like this when I've done a lot of `make test` and subsequently killing with ctrl-c. Basically, the sensors aren't being unloaded properly which ends up putting the system in a not-so-sane state. Any change that might be what's happening here?

2022-05-30 17:07 UTC, willfindlay requested changes
Linter caught this typo.

2022-05-30 17:07 UTC, willfindlay commented on bpf/process/bpf_generic_retkprobe.c
> +	 * 0x1000 should be maximum argument lenght, so masking
```suggestion
	 * 0x1000 should be maximum argument length, so masking
```

2022-05-30 17:32 UTC, olsajiri commented
> I've seen local test timeouts like this when I've done a lot of `make test` and subsequently killing with ctrl-c. Basically, the sensors aren't being unloaded properly which ends up putting the system in a not-so-sane state. Any change that might be what's happening here?

right, that could easily happened

2022-05-30 17:32 UTC, olsajiri commented on bpf/process/bpf_generic_retkprobe.c
> +	 * 0x1000 should be maximum argument lenght, so masking
right, I pushed new version, thanks

2022-05-30 21:03 UTC, willfindlay approved these changes

2022-05-31 07:58 UTC, kkourt approved these changes
🚀

2022-06-03 16:48 UTC, merged