tetragon: Allow to use data events for char_buf data
cilium/tetragon pull request #789
Opened 2023-03-10 15:44 UTC by olsajiri

Add support to use data events for char_buf data.

2023-03-10 16:45 UTC, olsajiri commented
static check fails on:
`CHECK:BIT_MACRO: Prefer using the BIT macro`

can be ignored

2023-03-14 12:00 UTC, kkourt requested changes
Thanks!

Can we add a warning for the cases where the configuration will be ignored from bpf side?

2023-03-15 10:01 UTC, olsajiri commented on pkg/sensors/tracing/generickprobe.go
> +		meta = meta | argMaxBit
makes sense, I just pushed the change

2023-03-30 08:45 UTC, mtardy reviewed
Do you think you could document this new feature in the TracingPolicy reference, in the argument paragraph, where we already talk about `char_buf` and `char_iovec`: https://tetragon.cilium.io/docs/reference/tracing-policy/#arguments ? Like how this thing interacts with `returnCopy` maybe as well, what's the difference.

2023-04-17 07:17 UTC, olsajiri commented on pkg/sensors/tracing/kprobe_test.go
> +  - call: "__x64_sys_write"
ok

2023-04-17 07:17 UTC, olsajiri commented on pkg/sensors/tracing/kprobe_test.go
> +  - call: "__x64_sys_write"
ok

2023-04-17 07:40 UTC, olsajiri commented
I rebased new version on top of https://github.com/cilium/tetragon/pull/885

2023-04-19 14:49 UTC, kkourt commented
> I rebased new version on top of #885

Thanks! It seems that it needs one more rebase now that #885 was merged :(

2023-04-27 08:13 UTC, kkourt approved these changes

2023-04-27 11:41 UTC, kkourt approved these changes

2023-04-27 12:22 UTC, merged