bug-report-template: add an issue template for bug report
cilium/tetragon pull request #898
Opened 2023-04-07 06:57 UTC by YTGhost

Fixes #894

2023-04-07 06:58 UTC, YTGhost commented
@mtardy PTAL

2023-04-07 08:35 UTC, mtardy requested changes
Thanks a lot for the work, I do appreciate but could you use the GitHub issue [YAMLs template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template) as [cilium/cilium is using for example](https://github.com/cilium/cilium/issues/new?assignees=&labels=kind%2Fcommunity-report%2Ckind%2Fbug%2Cneeds%2Ftriage&template=bug_report.yaml).

The file you can inspire from is here https://github.com/cilium/cilium/blob/master/.github/ISSUE_TEMPLATE/bug_report.yaml

2023-04-07 08:35 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.md
> +/kind bug
```suggestion
```

Not needed since we don't use Prow

2023-04-07 08:47 UTC, YTGhost commented
> Thanks a lot for the work, I do appreciate but could you use the GitHub issue [YAMLs template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms#yaml-issue-form-template) as [cilium/cilium is using for example](https://github.com/cilium/cilium/issues/new?assignees=&labels=kind%2Fcommunity-report%2Ckind%2Fbug%2Cneeds%2Ftriage&template=bug_report.yaml).
> 
> The file you can inspire from is here https://github.com/cilium/cilium/blob/master/.github/ISSUE_TEMPLATE/bug_report.yaml

Ok, thanks for the advice, I'll check it out

2023-04-15 12:12 UTC, YTGhost commented on .github/ISSUE_TEMPLATE/bug_report_template.md
> +/kind bug
ok

2023-04-15 12:12 UTC, YTGhost commented on .github/ISSUE_TEMPLATE/bug_report_template.md
> +- Others:
I see

2023-04-15 12:48 UTC, YTGhost commented
@mtardy PTAL

2023-04-17 08:23 UTC, mtardy reviewed
Thanks a lot that's great! :)

2023-04-17 08:23 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +labels: ["kind/community-report", "kind/bug", "needs/triage"]
```suggestion
labels: ["kind/bug"]
```
we don't have these labels for now

2023-04-17 08:23 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +        - Run `cilium sysdump` command
I think we can use `tetra bugtool` in place of `cilium sysdump`, cc @kkourt knows about this more than me.

2023-04-17 08:23 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +        Thanks for taking the time to fill out this bug report! If you have usage questions, please try the [slack channel](https://cilium.herokuapp.com/) and see the [FAQ](https://github.com/cilium/
Can you link to the Join the Slack using this URL: https://slack.cilium.io/
Can you link to the specific Tetragon Slack channel? https://cilium.slack.com/archives/C03EV7KJPJ9

Like "Join the Cilium Slack and ask questions in the Tetragon channel"

2023-04-17 08:23 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +      required: true
Can we make this optional since Tetragon can run standalone?

2023-04-24 17:27 UTC, mtardy reviewed
Thanks!!! Sorry, I missed this one last nit just before!

2023-04-24 17:27 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +      label: Tetra Version
```suggestion
      label: Tetragon Version
```

2023-04-24 17:27 UTC, mtardy commented
> @mtardy Apologies for not updating promptly due to the busyness of last week. PTAL.

Yeah no worries take your time!

2023-04-25 04:43 UTC, YTGhost commented
@mtardy PTAL

2023-04-25 07:40 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +      description: Which kernel version was Cilium running on? (run `uname -a`)
```suggestion
      description: Which kernel version was Tetragon running on? (run `uname -a`)
```

2023-04-25 07:40 UTC, mtardy commented on .github/ISSUE_TEMPLATE/bug_report_template.yaml
> +    id: tetra-version
```suggestion
    id: tetragon-version
```

2023-04-25 07:48 UTC, mtardy approved these changes
Thanks! Sorry for the back and forth!

2023-04-25 08:48 UTC, merged